// Game states
export const GAME_STATES = {
  MENU: 'menu',
  PLAYING: 'playing',
  PAUSED: 'paused',
  WON: 'won',
  LOST: 'lost',
  GAME_OVER: 'gameOver'
};

// Action types
export const ACTIONS = {
  START_GAME: 'START_GAME',
  GUESS_LETTER: 'GUESS_LETTER',
  UPDATE_TIMER: 'UPDATE_TIMER',
  PAUSE_GAME: 'PAUSE_GAME',
  RESUME_GAME: 'RESUME_GAME',
  END_GAME: 'END_GAME',
  RESET_GAME: 'RESET_GAME',
  SET_LEADERBOARD: 'SET_LEADERBOARD',
  ADD_SCORE: 'ADD_SCORE',
  TRIGGER_SHAKE: 'TRIGGER_SHAKE'
};

// Word list for the game
export const WORD_LIST = [
  'JAVASCRIPT', 'REACT', 'PROGRAMMING', 'COMPUTER', 'KEYBOARD',
  'MONITOR', 'SOFTWARE', 'HARDWARE', 'INTERNET', 'WEBSITE',
  'DATABASE', 'FUNCTION', 'VARIABLE', 'ALGORITHM', 'DEBUGGING',
  'FRONTEND', 'BACKEND', 'FRAMEWORK', 'LIBRARY', 'COMPONENT',
  'WINDSURF', 'VSCODE', 'GITHUB', 'NETLIFY', 'SQLITE'
];
